global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'chronos'
    static_configs:
      - targets: ['core-engine:8000'] 
    metrics_path: '/metrics'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-store:6379']

  - job_name: 'postgres'
    static_configs:
      - targets: ['db-store:5432']
